name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: check out code
        uses: actions/checkout@v2

      - name: restore mod cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: get dependencies
        run: go mod download

      - name: vet
        run: make vet

      - name: fmt-check
        run: make fmt-check

      - name: detect data races
        run: go test `go list ./... | grep -v test` -race -count=1

      - name: execute tests
        run: go test `go list ./... | grep -v test` -coverprofile=coverage.txt -covermode=atomic -count=1 -timeout 60s

      - name: upload code coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
