name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
          
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      - name: Get dependencies
        run: go get -v -t -d ./...
      
      - name: vet
        run: make vet

      - name: fmt-check
        run: make fmt-check

      - name: test
        run: make test

      - name: test-race
        run: make test-race

      - name: coverage
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
